import Head from 'next/head'
import s from '../src/styles/Home.module.css'
import Navbar from "../src/component/Navbar";


const indexNavigation = [
    {id: 1, title: 'Library', path: '/library'},
    {id: 2, title: 'Assistant', path: '/assistant'},
    {id: 3, title: 'Settings', path: '/settings'},
]


export default function Home() {
    return (
        <div className={s.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <main className={s.main}>
                <h1 className={'text-3xl'}>
                    Cheese Application
                </h1>
            </main>
            <Navbar navigation={indexNavigation}/>
        </div>
    )
}
