import Head from 'next/head'
import s from '../src/styles/Home.module.css'
import Navbar from "../src/component/Navbar";
import { PATH } from '../src/utils/appPath';

const indexNavigation = [
    {id: 1, title: 'Библиотека', path: PATH.LIBRARY.MAIN},
    {id: 2, title: 'Помощник', path: PATH.ASSISTANT.MAIN},
    {id: 3, title: 'Настройки', path: PATH.SETTINGS.MAIN},
]



const Home = () => {

    return (
        <div className='container'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <main className={s.main}>
                <h1 className={'text-3xl text-white'}>
                    Cheese Application
                </h1>
            </main>
            <Navbar navigation={indexNavigation}/>
        </div>
    )
}

export default Home
